# Generated by Django 3.2.4 on 2021-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210603_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
